---
- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
        
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
        
    - name: Install Maven
      apt:
        name: maven
        state: present
        
    - name: Add Jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes
        
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
