- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
        
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
        
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
        
    - name: Install Maven
      apt:
        name: maven
        state: present
        
    - name: Add current user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
        
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
