scrape_configs:
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins-host:8080']  # Replace with your Jenkins host
basic_auth:
  username: 'prometheus-monitor'
  password: '111ce465cbb2cf807f248d7ee8dc9bba08'      
