global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['account-service:8080']
      
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
