global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['account-service:8080']
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
basic_auth:
  username: 'prometheus-monitor'
  password: '111ce465cbb2cf807f248d7ee8dc9bba08'      
