global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'banking-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8091']  # For Mac/Windows
        # For Linux, use your machine's IP instead
